package-lock.json
package.json
src/components/floor-plan/floor-plan-crop.tsx
src/components/generic/spaces-map.tsx
src/components/screens/floor-plan-screen.tsx
src/types/index.ts

Feature 31 broken floor plan editor

---

src/components/layout/v2/alignment-editor-html.tsx
src/components/layout/v2/image-component-properties.tsx
src/components/layout/v2/layout-component-properties.tsx
src/components/layout/v2/margin-padding-editor-html.tsx
src/components/layout/v2/text-component-properties.tsx
src/components/preview/page-preview-html.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/utils/html-components-utils.ts
src/utils/html-resource-utils.ts
src/utils/localization-utils.ts

Fixed emphasis editor and added some tooltips

---

src/components/content-editor/content-accordion.tsx
src/components/content-editor/page-event-dialog.tsx
src/components/screens/content-editor-screen.tsx

Possible to add navigation events to pages

---

src/api/api.ts
src/components/dialogs/manage-device-dialog.tsx
src/components/floor-plan/floor-plan-info.tsx
src/components/generic/generic-dialog.tsx
src/components/generic/spaces-map.tsx
src/components/screens/content-editor-screen.tsx
src/components/screens/floor-plan-screen.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/utils/localization-utils.ts

Feature 46 initial fleet management

---

package-lock.json
package.json
src/components/layout/v2/layout-preview.tsx
src/components/preview/page-preview-html.tsx
src/components/screens/layout-screen-html.tsx

Changed layout text elements to automatically calculate max-width

---

src/components/content-editor/constants.ts
src/components/content-editor/content-accordion.tsx
src/components/content-editor/layout-view-resources-list.tsx
src/components/content-editor/resource-editor.tsx
src/components/layout/utils/tree-html-data-utils.ts
src/components/layout/v2/alignment-editor-html.tsx
src/components/layout/v2/button-component-properties.tsx
src/components/layout/v2/generic-component-properties.tsx
src/components/layout/v2/grouped-inputs-with-lock.tsx
src/components/layout/v2/image-button-component-properties.tsx
src/components/layout/v2/image-component-properties.tsx
src/components/layout/v2/layout-component-properties.tsx
src/components/layout/v2/layout-preview.tsx
src/components/layout/v2/layout-right-panel.tsx
src/components/layout/v2/proportions-editor-html.tsx
src/components/preview/page-preview-html.tsx
src/components/screens/content-editor-screen.tsx
src/components/screens/layout-screen-html.tsx
src/components/screens/layouts-screen.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/utils/html-components-utils.ts
src/utils/html-resource-utils.ts

Resolves #54 
Resolves #55 
Also fixes broken grouped inputs (margin/padding/border radius)

Feature background image

---

src/components/layout/v2/color-picker.tsx
src/components/layout/v2/generic-component-properties.tsx
src/components/layout/v2/layout-right-panel.tsx
src/utils/generic-utils.ts

Feature 57 store used colors to localstorage

---

src/components/screens/content-editor-screen.tsx
src/components/screens/layout-screen-html.tsx
src/utils/generic-utils.ts

Feature 59 disable layout code editor if user doesnt have developer role

---

package-lock.json
package.json
src/components/app.tsx
src/components/dialogs/delete-device-dialog.tsx
src/components/fleet-management/edit-device-drawer.tsx
src/components/fleet-management/fleet-management-table.tsx
src/components/generic/generic-dialog.tsx
src/components/generic/top-bar.tsx
src/components/screens/fleet-management-screen.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/types/index.ts
src/utils/generic-utils.ts

Feature 62 fleet management screen

---

src/components/dialogs/add-new-element-dialog.tsx
src/components/dialogs/add-new-layout-dialog.tsx
src/components/layout/v2/layout-component-properties.tsx
src/components/screens/layouts-screen.tsx
src/components/screens/rooms-screen.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Adds support for copying layouts
Hides some features not used by customer for clarity.

Feature copy layouts

---

src/components/layout/utils/tree-html-data-utils.ts
src/components/layout/v2/button-component-properties.tsx
src/components/layout/v2/layout-tree-menu-html.tsx
src/components/layout/v2/text-component-properties.tsx
src/constants/configuration.ts
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/types/index.ts
src/utils/html-components-utils.ts

Support for changing fonts

---

src/components/content-editor/dynamic-resource-editor.tsx
src/components/content-editor/dynamic-resource-switch-when-list.tsx
src/components/content-editor/media-library-button.tsx
src/components/content-editor/resource-editor.tsx
src/components/content-editor/tab-editor.tsx
src/components/content-editor/timeline-editor.tsx
src/components/generic/create-media-folder-dialog.tsx
src/components/right-panel-editors/media-library.tsx
src/components/screens/content-editor-screen.tsx
src/components/screens/floor-plan-screen.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/components/content-editor/timeline-editor.ts
src/styles/components/right-panel-editors/media-library.ts
src/utils/file-upload.ts
src/utils/file-utils.ts

Feature 77 support subfolders in media library

---

src/components/content-editor/timeline-devices-list.tsx
src/components/fleet-management/fleet-management-table.tsx
src/components/screens/fleet-management-screen.tsx
src/components/screens/floor-plan-screen.tsx
src/localization/fi.json

Hotfix 81 fleet management device list not showing name

---

src/components/right-panel-editors/media-library.tsx
src/utils/file-utils.ts

Fixed issue #84

---

src/components/right-panel-editors/media-library.tsx
src/utils/file-utils.ts

Fixed issue #86

---

src/components/screens/content-versions-screen.tsx

Fixed issue with creating new content versions

---

src/components/right-panel-editors/media-library.tsx
src/components/screens/content-versions-screen.tsx

Bugfix 93 cannot deselect media

---

src/components/screens/content-versions-screen.tsx

Bugfix 91 content version deletion

---

src/components/screens/floor-plan-screen.tsx
src/styles/components/right-panel-editors/media-library.ts

Fixed issue with media library using ellipsis instead of break word

---

src/components/right-panel-editors/media-library.tsx

Fixes issues with medialibrary deselection with url functions

---

src/components/content-editor/timeline-devices-list.tsx

Fixed issue #102

---

src/components/screens/content-editor-screen.tsx
src/components/screens/content-versions-screen.tsx

Bugfix 104 missing breadcrumbs from content edit screen

---

package-lock.json
package.json
src/components/content-editor/content-accordion.tsx
src/components/content-editor/layout-view-resources-list.tsx
src/components/content-editor/resource-editor.tsx
src/components/dialogs/delete-device-dialog.tsx
src/components/layout/v2/color-picker.tsx
src/components/layout/v2/generic-component-properties.tsx
src/components/layout/v2/layout-right-panel.tsx
src/components/layout/v2/text-component-properties.tsx
src/components/screens/content-editor-screen.tsx
src/components/screens/layout-screen-html.tsx
src/components/screens/layouts-screen.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/utils/generic-utils.ts
src/utils/html-components-utils.ts
src/utils/html-resource-utils.ts
src/utils/localization-utils.ts

Feature 106 support for changing layout element background colors per page

---

src/components/content-editor/constants.ts
src/components/layout/v2/video-component-properties.tsx
src/utils/html-resource-utils.ts

- Also separates video autoplay and loop

Bugfix not able to edit videos in content editor screen

---

src/components/content-editor/resource-editor.tsx
src/components/right-panel-editors/media-library.tsx

- Also fixed compile issues in resource-editor.tsx

Fixed not being able to deselect page media resource

---

src/components/fleet-management/fleet-management-table.tsx
src/components/floor-plan/floor-plan-info.tsx
src/components/screens/fleet-management-screen.tsx

Feature 119 sort devices in floor plan management

---

src/components/screens/device-models-screen.tsx

Allow empty fields in device model dialog

---

.gitignore
src/types/index.ts

Added support for joystick buttons A, X and Y

---

src/components/dialogs/add-new-layout-dialog.tsx
src/components/screens/content-editor-screen.tsx
src/components/screens/layouts-screen.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/utils/html-resource-utils.ts

Added support for creating new legacy layouts

---

src/components/layout/utils/tree-data-utils.ts
src/utils/resource-utils.ts

Added web view element resource type to be text
